### ISSUE TITLE
有没有同步方式的REST方法？

### ISSUE THREAD

**Issue by easondsh** [HuobiRDCenter/huobi_CSharp#1]
key.json里的account id是什么

**Comment by eynzhang** [comment]
@easondsh , 异步方法是兼容同步方法的，文档里有说明和例子：

The method for all Rest Client is asynchronism, it invoke Huobi asynchronous and returns a Task immediately without blocking further statements. If you would like to get the result synchronous, just simply access its Result property, it will be blocked until the data is returned.

关于配置文件中的account id，是appsettings.json里定义的，是测试时为了方便一次性配置好的，实际应用时可能需要从API动态取得。有些API需要这个参数，具体的可以参考account id被哪些地方应用，或者参考API文档。
